server:
    host: '0.0.0.0'
    port: 3000
    debug: True
    environment: development
    testing: False
    use_reloader: True

security:
    auth:
        required: True
        add_key_to_claims: True
        allow_expired: False
        audience: null
        claim_identity: sub
        claim_issuer: iss
        algorithms:
          - RS256
        validation_methods:
          - userinfo
          - public_key
        validation_checks: all

api:
    specs:
        - path: petstore.yaml
          append: null
          add_operation_fields:
              x-openapi-router-controller: controllers
          connexion:
              strict_validation: True
              validate_responses: False
              options:
                  swagger_ui: True
                  serve_spec: True

db:
    host: mongodb
    port: 27017
    dbs:
        petstore:
            collections:
                pets:
                    indexes: null

exceptions:
    required_members: [['message'], ['code']]
    status_member: ['code']
    exceptions: exceptions.exceptions
